tide-whisperer.go
@kentquirk @jebeck return it all and don't require that an uploadId is contained for each item
=> don't filter out items that don't have an uploadId

tide-whisperer.go
Possible solution to the sort index issue -- @jh-bate ?
=> Make sort use the same fields as the index

config/server.json, tide-whisperer.go
@darinkrauss here is the change for using the schema version
=> addition of schemaVersion check and update index

config/server.json
@jh-bate this is what we'll need for bootstrapping, right?
=> update min and max _schemaVersion for BtUTC

config/server.json
=> Pool-whisperer replaced with tide-whisperer

Comedeps, gotest, store_test.go, test.sh
@jh-bate Same as previous tide-whisperer PR, just rebased upon latest changes in master.
=> Use latest go-common; remove broken tests (due to MongoDB/mgo mismatch); update test scripts

config/server.json
Please see synchronize_databases/README.md in the tools repo for more information.
@jh-bate
=> Synchronize database and collection names between localhost and deployed

Dockerfile
Initial version of Dockerfile published to https://hub.docker.com/r/tidepool/tide-whisperer/
=> Add `Dockerfile` to support creation of a tide-whisperer container

.travis.yml, Dockerfile
=> Update to Go 1.9.1; fix Dockerfile build script

store/store.go
=> Fix edge case with Dexcom API that results in no data returned

version.sh
@jh-bate Need a quick review here.
=> Need to update version.sh for build to create artifact

store/store.go, store/store_test.go
=> Return other CGM data after latest Dexcom API data

tide-whisperer.go
=> Release 0.11.0

tide-whisperer.go, vendor/github.com/tidepool-org/go-common/clients/hakken/hakken.go
This adds a feature flag to skip starting the hakken service.
=> Added feature flag to skip hakken service.

tide-whisperer.go
Skip hakken in env if set.
Use top level env variables if set.
=> Kubernetes mods

store/store.go, tide-whisperer.go
* Add contextual messages to Mongo errors logged
* Add `Disconnect` method
=> [BACK-355] Improve startup error handling

store/store.go, store/store_test.go, tide-whisperer.go
* Fixes [BACK-1268]
[BACK-1268]: https://tidepool.atlassian.net/browse/BACK-1268
=> [BACK-1268]: Improve `latest` aggregate query 

tide-whisperer.go
First of three step process to add prefixes.
Remove unneeded guards for Gloo function discovery.  Function discovery can be turned off.
=> Add prefix /data

tide-whisperer.go
* Fixes [BACK-1777]
[BACK-1777]: https://tidepool.atlassian.net/browse/BACK-1777
=> [BACK-1777] Stop log spam relating to signals

store/store.go, store/store_test.go
See [BACK-1916] for details
[BACK-1916]: https://tidepool.atlassian.net/browse/BACK-1916
=> [BACK-1916] Fix formatting of mongo date range queries to use a reliably sortable format

store/store.go, store/store_test.go
Reverts tidepool-org/tide-whisperer#97
=> Revert "[BACK-1746] Convert string dates to ISODATE in DB"
